import useSWR from 'swr'
import { useRouter } from 'next/router'
import { supabase } from '../lib/supabaseClient'
import { useEffect } from 'react'
const fetcher = (url) => fetch(url, { credentials: 'include' }).then(r=>{ if(r.status===401) throw new Error('unauth'); return r.json() })
export default function Dashboard(){ const router = useRouter(); const { data, error, mutate } = useSWR('/api/wallets', fetcher)
  useEffect(()=>{ supabase.auth.getSession().then(({data})=>{ if(!data.session) router.push('/auth/login') }) }, [])
  if(!data) return <div style={{minHeight:'100vh',display:'flex',alignItems:'center',justifyContent:'center'}}>Loading...</div>
  const wallets = data.wallets
  return (<div style={{padding:24}}><div style={{maxWidth:980,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h1>Your Wallets</h1><div><button onClick={async()=>{ await fetch('/api/auth/logout',{method:'POST',credentials:'include'}); await supabase.auth.signOut(); router.push('/auth/login') }} style={{padding:8,background:'#f59e0b',borderRadius:8}}>Logout</button></div></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:12,marginTop:16}}>{['BTC','ETH','USDT'].map(sym=>(<div key={sym} style={{padding:12,background:'#07182a',borderRadius:10}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:6}}><div><strong>{sym}</strong><div style={{fontSize:12,color:'#9aa'}}>Wallet</div></div><div style={{fontFamily:'monospace'}}>{wallets[sym].balance}</div></div><div style={{fontSize:12,color:'#9aa',marginBottom:8}}>Address: {wallets[sym].address || <em style={{color:'#6b7280'}}>not set</em>}</div><div style={{display:'flex',gap:8}}><button style={{flex:1}} onClick={async()=>{ const a=prompt('Set address',wallets[sym].address||''); if(a!=null){ await fetch('/api/wallets',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'setAddress',symbol:sym,address:a})}); mutate() }}}>Set Address</button><button style={{background:'#16a34a'}} onClick={async()=>{ const a=prompt('Amount to receive'); if(a){ await fetch('/api/wallets',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'adjust',symbol:sym,delta:Number(a)})}); mutate() }}}>Receive</button><button style={{background:'#ef4444'}} onClick={async()=>{ const a=prompt('Amount to send'); if(a){ await fetch('/api/wallets',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'adjust',symbol:sym,delta:-Number(a)})}); mutate() }}}>Send</button></div></div>))}</div></div></div>)}
